name: Build/release

on: push

env:
  CSC_LINK: ${{ secrets.CSC_LINK }}
  # CSC_WINDOWS_LINK: ${{ secrets.CSC_WINDOWS_LINK }}
  CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
  APPLEID: ${{ secrets.APPLEID }}
  APPLEIDPASS: ${{ secrets.APPLEIDPASS }}


jobs:
  # run_if:
  #   if:  startsWith(github.ref, 'refs/tags/v')

  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]
        # os: [macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.0

      - name: Install dependencies
        run: |
          npm i lerna@3.8
          npx lerna bootstrap

      - name: Build App
        run: npm run build

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: |
            out
            !out/**/Franz.app
